### ISSUE TITLE
not in npm registry

### ISSUE THREAD

**Issue by vogloblinsky** [filso/ng-dependency-lint#1]
Could you please add the project in npm registry, and update package.json name with "ng-dependency-lint" instead of "ng-d-lint"

Thanks

**Comment by vogloblinsky** [comment]
`npm install --save-dev https://github.com/filso/ng-dependency-lint/tarball/master`

This command works until a new release is available.

**Comment by Chris2011** [comment]
I used ng-d-lint.

**Comment by filso** [comment]
hi guys, sorry, but I think I'll just abandon this project, for the lack of time to maintain it.
ESLint is doing something similar, and it's better:
https://www.npmjs.com/package/eslint-plugin-angular
