### ISSUE TITLE
ng-dependency-lint is not recognized

### ISSUE THREAD

**Issue by bp117** [filso/ng-dependency-lint#2]
when I try to run the linter from command prompt I am getting below error

ng-dependency-lint is not recognized as internal or external command

**Comment by filso** [comment]
Hi
Thanks for feedback
This was a bit neglected by me, sorry for that. I'm thinking of deprecating it in favor of eslint:
https://github.com/Gillespie59/eslint-plugin-angular/blob/master/docs/di-unused.md
